#!/usr/bin/env python3
"""Regenerate LuaUI/Configs/widgets_only_defs.lua.

The widgets in this folder read a few unit/weapon def values that the source
branch added to units/*.lua and gamedata/modularcomms/weapons/*.lua. Official
releases don't have them, so they are collected here into a table that
api_widgets_only_defs.lua writes into UnitDefs/WeaponDefs customParams.

Usage (from the repo root):
    python3 LocalWidgets/tools/gen_widgets_only_defs.py [source-ref] [base-ref]
Defaults: origin/claude/combined-branch-merge-04k37p, origin/master.
"""
import re
import subprocess
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "origin/claude/combined-branch-merge-04k37p"
BASE = sys.argv[2] if len(sys.argv) > 2 else "origin/master"
OUT = "LocalWidgets/LuaUI/Configs/widgets_only_defs.lua"

UNIT_KEYS = {"overlay_icon_size", "health_bar_height", "energy_grid", "teleporter_is_beacon"}
WEAPON_KEYS = {"icon"}


def git(*args):
	return subprocess.run(["git", *args], check=True, capture_output=True, text=True).stdout


def added_lines(path):
	"""Line numbers (in SRC) added relative to BASE."""
	out = git("diff", "-U0", BASE, SRC, "--", path)
	lines = set()
	for m in re.finditer(r"^@@ -\S+ \+(\d+)(?:,(\d+))? @@", out, re.M):
		start, count = int(m.group(1)), int(m.group(2) or "1")
		lines.update(range(start, start + count))
	return lines


def lua_value(raw):
	raw = re.sub(r"\s*--.*$", "", raw)
	raw = raw.strip().rstrip(",").strip()
	m = re.fullmatch(r"\[\[(.*)\]\]", raw)
	if m:
		return m.group(1)
	m = re.fullmatch(r"\"(.*)\"", raw)
	if m:
		return m.group(1)
	if raw in ("true", "false"):
		return raw == "true"
	return float(raw) if "." in raw else int(raw)


def parse_unit_file(path, units, weapons):
	text = git("show", f"{SRC}:{path}")
	new = added_lines(path)
	stack = []
	for lineno, line in enumerate(text.splitlines(), 1):
		code = re.sub(r"--.*$", "", line)
		m = re.match(r"\s*(?:return\s*\{\s*)?\[?\"?([A-Za-z0-9_]+)\"?\]?\s*=\s*\{", code)
		opened = code.count("{")
		closed = code.count("}")
		if m:
			stack.append(m.group(1))
			opened -= 1
			if code.lstrip().startswith("return"):
				opened -= 1  # the outer `return {` wrapper
		# anonymous tables ({ def = ..., }) still need a stack slot
		stack.extend([None] * opened)
		if lineno in new:
			kv = re.match(r"\s*([A-Za-z_]+)\s*=\s*(.+)$", line)
			if kv:
				key, val = kv.group(1), kv.group(2)
				path_l = [s.lower() for s in stack if s]
				if key == "iconType" and len(path_l) == 1:
					units.setdefault(path_l[0], {})["iconType"] = lua_value(val)
				elif key in UNIT_KEYS and len(path_l) == 2 and path_l[1] == "customparams":
					units.setdefault(path_l[0], {})[key] = lua_value(val)
				elif key in WEAPON_KEYS and len(path_l) == 4 and path_l[1] == "weapondefs" and path_l[3] == "customparams":
					weapons[path_l[0] + "_" + path_l[2]] = lua_value(val)
		for _ in range(closed):
			if stack:
				stack.pop()


def parse_comm_weapons(comm):
	files = git("ls-tree", "--name-only", SRC, "gamedata/modularcomms/weapons/").split()
	info = {}
	for path in files:
		text = git("show", f"{SRC}:{path}")
		name = re.search(r"local name = \"([^\"]+)\"", text) or re.search(r"return \"([^\"]+)\"", text)
		icon = re.search(r"(?:^\s*|\.)icon\s*=\s*\[\[([^\]]+)\]\]", text, re.M)
		base = re.search(r"VFS.Include\(\"(gamedata/modularcomms/weapons/[^\"]+)\"\)", text)
		info[path] = (name and name.group(1), icon and icon.group(1), base and base.group(1))
	for path, (name, icon, base) in info.items():
		while not icon and base in info:
			_, icon, base = info[base]
		if name and icon:
			comm[name] = icon


def lua_literal(v):
	if isinstance(v, bool):
		return "true" if v else "false"
	if isinstance(v, (int, float)):
		return repr(v)
	return "[[" + v + "]]"


def main():
	units, weapons, comm = {}, {}, {}
	for path in git("diff", "--name-only", BASE, SRC, "--", "units").split():
		parse_unit_file(path, units, weapons)
	parse_comm_weapons(comm)

	out = [
		"-- Generated by LocalWidgets/tools/gen_widgets_only_defs.py from " + SRC + ". Do not edit by hand.",
		"-- Def values the widgets expect but official releases don't define.",
		"-- Applied to UnitDefs/WeaponDefs by api_widgets_only_defs.lua.",
		"return {",
		"\t-- unitDef name -> customParams (plus iconType, the radar icon to use)",
		"\tunits = {",
	]
	for name in sorted(units):
		fields = ", ".join(f"{k} = {lua_literal(v)}" for k, v in sorted(units[name].items()))
		out.append(f"\t\t{name} = {{{fields}}},")
	out += ["\t},", "\t-- weaponDef name -> customParams.icon (reload badge icon)", "\tweaponIcons = {"]
	for name in sorted(weapons):
		out.append(f"\t\t[\"{name}\"] = {lua_literal(weapons[name])},")
	out += ["\t},", "\t-- modular commander weapon (matched as a weaponDef name suffix) -> customParams.icon", "\tcommWeaponIcons = {"]
	for name in sorted(comm):
		out.append(f"\t\t{name} = {lua_literal(comm[name])},")
	out += ["\t},", "}", ""]
	with open(OUT, "w") as f:
		f.write("\n".join(out))
	print(f"{OUT}: {len(units)} units, {len(weapons)} weapons, {len(comm)} comm weapons")


main()
